name: timlarsen
favicon: null
layout_spectrum: 0.10816434700973332
typography_spectrum: 0.04532679542899132
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.12418735329993069
  lightness: 0.9062128579244018
  saturation: 0.8963101769331843
  rhythmicContrast: 0.5611904300749302
purpose: []
